[package]
name = "rusty-slack-emoji-statistics"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = { version = "2" }
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.10.1", features = ["full"] }

[dev-dependencies]
pretty_assertions = "*"
